(function() { var sess = sessionStorage.getItem('wanago_session'); if (sess) { window.location.replace('pages/dashboard.html'); } })();
const FB_BASE = 'https://www.gstatic.com/firebasejs/10.12.0';
const FB_CFG = { apiKey:"AIzaSyCRm_YW-TsVvzpF3SC275ZeLqr-0n2ZzvU", authDomain:"wanago-erp.firebaseapp.com", projectId:"wanago-erp", storageBucket:"wanago-erp.firebasestorage.app", messagingSenderId:"445920648182", appId:"1:445920648182:web:2ef6f9110767bc9f36c5d7" };
let _app=null,_auth=null,_db=null;
async function _init(){ if(_app) return {auth:_auth,db:_db}; const [{initializeApp},{getAuth},{getFirestore}]=await Promise.all([import(FB_BASE+'/firebase-app.js'),import(FB_BASE+'/firebase-auth.js'),import(FB_BASE+'/firebase-firestore.js')]); _app=initializeApp(FB_CFG);_auth=getAuth(_app);_db=getFirestore(_app); return {auth:_auth,db:_db}; }
async function handleLogin(){ var email=(document.getElementById('login-email')?.value||'').trim(),password=document.getElementById('login-password')?.value||'',btn=document.getElementById('login-btn'); if(!email||!password){showMsg('Please enter email and password.',false);return;} btn.textContent='Signing in...';btn.disabled=true; try{ const {auth}=await _init(); const {signInWithEmailAndPassword}=await import(FB_BASE+'/firebase-auth.js'); const cred=await signInWithEmailAndPassword(auth,email,password); doLogin({id:cred.user.uid,name:cred.user.displayName||'Admin',email:email,role:'founder',dept:'leadership',officeId:'*',systemRole:'founder_ceo'},email,btn); }catch(e){ var errs={'auth/wrong-password':'Wrong password.','auth/invalid-credential':'Wrong email or password.','auth/too-many-requests':'Too many attempts. Try again later.','auth/user-not-found':'No account found.'}; showMsg(errs[e.code]||'Login failed. Try again.',false); btn.textContent='Sign In';btn.disabled=false; } }
function doLogin(member,email,btn){ var session={uid:member.id||'t1',name:member.name||'Admin',email:email,role:member.role||'founder',dept:member.dept||'leadership',officeId:member.officeId||'*',systemRole:member.systemRole||'founder_ceo',loginTime:new Date().toISOString()}; sessionStorage.setItem('wanago_session',JSON.stringify(session)); showMsg('Welcome '+session.name+'!',true); setTimeout(function(){window.location.href='pages/dashboard.html';},500); }
function handleForgotPassword(){ var email=(document.getElementById('login-email')?.value||'').trim(); if(!email){showMsg('Enter your email first.',false);return;} _init().then(function(fb){return import(FB_BASE+'/firebase-auth.js').then(function(m){return m.sendPasswordResetEmail(fb.auth,email);});}).then(function(){showMsg('Reset email sent! Check your inbox.',true);}).catch(function(){showMsg('Could not send reset email.',false);}); }
function togglePassword(){ var input=document.getElementById('login-password'),b=document.querySelector('.toggle-pw'); if(!input)return; if(input.type==='password'){input.type='text';if(b)b.textContent='??';}else{input.type='password';if(b)b.textContent='??';} }
function showMsg(msg,ok){ var el=document.getElementById('login-error'); if(!el)return; el.textContent=msg;el.style.display='block';el.style.padding='10px 14px';el.style.borderRadius='8px';el.style.fontSize='13px';el.style.marginTop='10px';el.style.background=ok?'rgba(34,128,80,.08)':'rgba(192,57,43,.08)';el.style.color=ok?'#1a6341':'#c0392b';el.style.border='1px solid '+(ok?'rgba(34,128,80,.2)':'rgba(192,57,43,.2)'); }
function onKeyDown(e){if(e.key==='Enter')handleLogin();}
window.handleLogin=handleLogin;window.handleForgotPassword=handleForgotPassword;window.togglePassword=togglePassword;window.onKeyDown=onKeyDown;
