import { where, type QueryConstraint } from "firebase/firestore";
import { campaignRepository } from "@/modules/campaigns/services/campaign.repository";
import { FIRESTORE_COLLECTIONS } from "@/lib/constants";
import { toDate } from "@/lib/utils/helpers";
import { nextRefNumber } from "@/lib/firebase/ref-counter";
import type { Campaign, CampaignFormData } from "@/modules/campaigns/types";
import { collection, query, getCountFromServer, Timestamp } from "firebase/firestore";
import { db } from "@/lib/firebase/client";

// Note: sorted client-side (not via Firestore orderBy) so filtered
// queries only need single-field indexes, which Firestore creates
// automatically — no manual composite index deployment required.
export async function fetchCampaigns(filters?: {
  officeId?: string;
  campaignStatus?: string;
}): Promise<Campaign[]> {
  const constraints: QueryConstraint[] = [];
  if (filters?.officeId)       constraints.push(where("officeId",       "==", filters.officeId));
  if (filters?.campaignStatus) constraints.push(where("campaignStatus", "==", filters.campaignStatus));
  const campaigns = await campaignRepository.findMany({ constraints });
  return campaigns.sort((a, b) => (toDate(b.createdAt)?.getTime() ?? 0) - (toDate(a.createdAt)?.getTime() ?? 0));
}

export async function fetchCampaignById(id: string): Promise<Campaign | null> {
  return campaignRepository.findById(id);
}

export async function createCampaign(
  data: CampaignFormData,
  createdBy: string
): Promise<Campaign> {
  const refNumber = await nextRefNumber("CAMPAIGN");

  return campaignRepository.create({
    ...data,
    refNumber,
    createdBy,
    status:       "active",
    endDate:      data.endDate ?? null,
    budget:       data.budget ?? null,
    notes:        data.notes || null,
    campaignType: data.campaignType || "",
  });
}

export async function updateCampaign(
  id: string,
  data: Partial<CampaignFormData>
): Promise<void> {
  return campaignRepository.update(id, data as Partial<Campaign>);
}

export async function deleteCampaign(id: string): Promise<void> {
  return campaignRepository.delete(id);
}

/**
 * Read-only metric: counts how many leads were generated by a given
 * campaign, matched by channel === lead.source and createdAt falling
 * within the campaign's date range. Uses Firestore's count() aggregation
 * (billed as a single read regardless of match count) instead of
 * downloading the entire Leads collection just to .filter().length it —
 * requires a composite index on leads(source, createdAt), added to
 * firestore.indexes.json alongside this change.
 */
export async function countLeadsForCampaign(campaign: Campaign): Promise<number> {
  try {
    const start = toDate(campaign.startDate);
    if (!start) return 0;

    const constraints: QueryConstraint[] = [
      where("source", "==", campaign.channel),
      where("createdAt", ">=", Timestamp.fromDate(start)),
    ];
    const end = campaign.endDate ? toDate(campaign.endDate) : null;
    if (end) constraints.push(where("createdAt", "<=", Timestamp.fromDate(end)));

    const snap = await getCountFromServer(query(collection(db, FIRESTORE_COLLECTIONS.LEADS), ...constraints));
    return snap.data().count;
  } catch {
    return 0;
  }
}
