import { where, type QueryConstraint } from "firebase/firestore";
import { campaignRepository } from "@/modules/campaigns/services/campaign.repository";
import { FIRESTORE_COLLECTIONS } from "@/lib/constants";
import { toDate } from "@/lib/utils/helpers";
import { nextRefNumber } from "@/lib/firebase/ref-counter";
import type { Campaign, CampaignFormData } from "@/modules/campaigns/types";
import { collection, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase/client";

// Note: sorted client-side (not via Firestore orderBy) so filtered
// queries only need single-field indexes, which Firestore creates
// automatically — no manual composite index deployment required.
export async function fetchCampaigns(filters?: {
  officeId?: string;
  campaignStatus?: string;
}): Promise<Campaign[]> {
  const constraints: QueryConstraint[] = [];
  if (filters?.officeId)       constraints.push(where("officeId",       "==", filters.officeId));
  if (filters?.campaignStatus) constraints.push(where("campaignStatus", "==", filters.campaignStatus));
  const campaigns = await campaignRepository.findMany({ constraints });
  return campaigns.sort((a, b) => (toDate(b.createdAt)?.getTime() ?? 0) - (toDate(a.createdAt)?.getTime() ?? 0));
}

export async function fetchCampaignById(id: string): Promise<Campaign | null> {
  return campaignRepository.findById(id);
}

export async function createCampaign(
  data: CampaignFormData,
  createdBy: string
): Promise<Campaign> {
  const refNumber = await nextRefNumber("CAMPAIGN");

  return campaignRepository.create({
    ...data,
    refNumber,
    createdBy,
    status:       "active",
    endDate:      data.endDate ?? null,
    budget:       data.budget ?? null,
    notes:        data.notes || null,
    campaignType: data.campaignType || "",
  });
}

export async function updateCampaign(
  id: string,
  data: Partial<CampaignFormData>
): Promise<void> {
  return campaignRepository.update(id, data as Partial<Campaign>);
}

export async function deleteCampaign(id: string): Promise<void> {
  return campaignRepository.delete(id);
}

/**
 * Read-only metric: counts how many leads were generated by a given
 * campaign, matched by channel === lead.source and createdAt falling
 * within the campaign's date range. Computed entirely client-side from
 * a full leads fetch (mirrors the fetch-all-then-reduce pattern used in
 * modules/dashboard/services/dashboard.service.ts) so no composite
 * Firestore index or change to the leads module is required.
 */
export async function countLeadsForCampaign(campaign: Campaign): Promise<number> {
  try {
    const snap = await getDocs(collection(db, FIRESTORE_COLLECTIONS.LEADS));
    const leads = snap.docs.map(d => d.data());

    const start = toDate(campaign.startDate);
    const end   = campaign.endDate ? toDate(campaign.endDate) : null;

    return leads.filter(l => {
      if (l.source !== campaign.channel) return false;
      const created = toDate(l.createdAt);
      if (!created || !start) return false;
      if (created < start) return false;
      if (end && created > end) return false;
      return true;
    }).length;
  } catch {
    return 0;
  }
}
